blank_issues_enabled: false
contact_links:
  - name: ğŸ’ Discussion
    url: https://github.com/Fnedx/Fnedx.github.io/discussions
    about: 'This issue tracker is not for support questions. Leave a comment on the discussion board if you need help.'
